version: '3'
services:
  app:
    image: mk51/devops-app:cached
    ports:
      - "8080:8080"
    environment:
      - NODOS_HOST=0.0.0.0
    depends_on:
      - db 

  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

  caddy:
    image: caddy:2.3.0-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
