version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: "npm test"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data


