version: '3'
services:
  app:
    ports:
      - "8080:8080"
    volumes:
    - ./:/app

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
