version: '3'
services:
  app:
    command: npm start
    ports:
      - "8080:8080"
    volumes:
       - ./:/app
    environment:
      - NODOS_HOST=0.0.0.0
    depends_on:
      - postgres

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    restart:
      - always
    depends_on:
      - app

  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  pgdata:

