version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    entrypoint: "./entrypoint.sh db npm start"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
