version: '3'
services:
  app:
    command: npm start
    ports:
      - "8080:8080"
    volumes:
       - ./:/app
    environment:
      - NODOS_HOST=0.0.0.0
    depends_on:
      - db

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
  pgdata:

